package report

import part6.GeneralCase
import trace.ExecutionLog
import trace.Report
import trace.ReportBuilder

data class StructuredReport(
    val mainResults: String,
    val contractionResults: String,
    val periodicResults: String,
    val intermediateResults: String
)

fun buildStructuredReport(V: List<Int>, p: Int, log: ExecutionLog): StructuredReport {
    val periode = GeneralCase.findMinimalPeriod(V, p, log)
    val report = ReportBuilder.fromExecutionLogToReport(log)
    val Q = report.inputParams.v0
    val p = report.inputParams.p
    val jj0 = report.stepList[p].j

    return StructuredReport(
        mainResults = buildMainResult(Q, p, periode, jj0),
        contractionResults = buildContractionResults(report, p),
        periodicResults = buildPeriodicResults(report),
        intermediateResults = buildIntermediateResults(report, p)
    )
}

private fun buildMainResult(Q: List<Int>, p: Int, periode: Long, jj0: Long): String {
    val sb = StringBuilder()

    sb.append("Start values: Q = $Q, p = $p\n")
    sb.append("\n")
    sb.append("Main result: $periode is the minimal period of the shift symmetric ")
    sb.append("bitstring generated by Q = $Q and p = $p, ")
    sb.append("and $jj0 is the least even vector period of the corresponding vector representation")

    return sb.toString()
}

private fun buildContractionResults(report: Report, p: Int): String {
    val sb = StringBuilder()
    val pii = report.contractList[0].pi
    sb.append("Q[$p] = $pii\n")

    if (p > 0) {
        for (i in 0..p - 1) {
            val r = report.contractList[i].r
            val tau = report.contractList[i].tau
            val ii = p - i
            val tvector = mutableListOf<Int>()
            val rsize = r.size

            for (j in 0..rsize - 1) {
                tvector.add(tau[r[j]])
            }

            sb.append("tau = $tau, r = $r\n")
            sb.append("tau[r] = tau$r = $tvector\n")
            val inew = ii - 1
            val pinew = report.contractList[i + 1].pi
            sb.append("\n")
            sb.append("Q[$inew] = (")
            for (j in 0..rsize - 3) {
                val aux1 = tau[r[j + 1]]
                val aux0 = tau[r[j]]
                sb.append("$aux1 - $aux0, ")
            }
            val auxy1 = tau[r[rsize - 1]]
            val auxy0 = tau[r[rsize - 2]]
            sb.append("$auxy1 - $auxy0 + 1) = ")
            sb.append("$pinew\n")
        }
    }

    sb.append("\n")
    sb.append("Comment: Q[$p] = Q and Q[i-1] is the contraction of Q[i] for 1 <= i <= $p")
    return sb.toString()
}

private fun buildPeriodicResults(report: Report): String {
    val sb = StringBuilder()

    for (i in report.stepList.indices) {
        val zeta = report.stepList[i].zeta
        val j = report.stepList[i].j
        val V = report.stepList[i].v
        sb.append("p-value = $i,   Q[$i] = $V,   j[$i] = $j,   zeta[$i] = $zeta\n")
    }
    sb.append("\n")
    sb.append("Comment: Suppose 0 <= i <= p. Then zeta[i] is the minimal period ")
    sb.append("of the shift symmetric bitstring generated by Q[i] and p = i, and ")
    sb.append("j[i] is the least even vector period of the corresponding vector representation.")
    return sb.toString()
}

private fun buildIntermediateResults(report: Report, p: Int): String {
    val dot = "\u00B7"
    val sb = StringBuilder()

    sb.append("Step 0:\n")
    val j = report.stepList[0].j
    val zeta = report.stepList[0].zeta
    val Q = report.stepList[0].v
    val Qext = Q.toMutableList()
    val lastIdx = Qext.size - 1
    Qext[lastIdx] = Qext[lastIdx] + 1
    sb.append("j[0] = $j and zeta[0] = $zeta are the cyclic parameters of\n")
    sb.append("the extension $Qext of Q[0] = $Q\n")

    for (i in 1..p) {
        sb.append("\n")
        sb.append("Step $i:\n")
        val jPrev = report.stepList[i - 1].j
        val zetaPrev = report.stepList[i - 1].zeta
        val jCurr = report.stepList[i].j
        val zetaCurr = report.stepList[i].zeta
        val QCurr = report.stepList[i].v
        val gamma = report.stepList[i].gamma
        val m = i - 1

        if (gamma != null && gamma == 0) {
            sb.append("Q[$i] = $QCurr, j[$i] = j[$m] = $jPrev, zeta[$i] = zeta[$m] + j[$i]) = $zetaPrev + $jCurr = $zetaCurr\n")
        }

        if (gamma != null && gamma > 0) {
            val c = report.stepList[i].c
            val tau2 = report.stepList[i].tau
            val d = report.stepList[i].d
            sb.append("Q[$i] = $QCurr\n")
            sb.append("C[$i] = $c\n")
            sb.append("tau = $tau2, \n")

            if (c != null && c.size > 1) {
                val auxx = c[1]
                sb.append("D[$i] = [tau($auxx)")
                if (gamma > 2) {
                    for (a in 2..gamma - 1) {
                        if (a < c.size) {
                            val aux = c[a]
                            sb.append(", tau($aux)")
                        }
                    }
                }
                if (gamma < c.size) {
                    val auxy = c[gamma]
                    if (gamma > 1) {
                        sb.append(", tau($auxy)")
                    }
                }
                sb.append("] = $d\n")
            } else {
                sb.append("D[$i] = [] = $d\n")
            }

            val alpha = report.stepList[i].alpha
            val alphaStar = report.stepList[i].alphaStar
            val gammaStar = report.stepList[i].gammaStar
            sb.append("gamma[$i] = $gamma, alpha[$i] = $alpha, gamma*[$i] = $gammaStar, alpha*[$i] = $alphaStar\n")
            val g = report.stepList[i].g
            val x = report.stepList[i].x
            val y = report.stepList[i].y
            sb.append("g = gcd(alpha*[$i], zeta[$m]) = gcd($alphaStar, $zetaPrev) = $g\n")
            sb.append("x = zeta[$m]/g = $zetaPrev/$g = $x, y = alpha*[$i]/g = $alphaStar/$g = $y\n")
            sb.append("j[$i] = 2 $dot x $dot gamma*[$i] + y $dot j[$m] = 2 $dot $x $dot $gammaStar + $y $dot $jPrev = $jCurr\n")
            sb.append("zeta[$i] = y $dot zeta[$m] + j[$i] = $y $dot $zetaPrev + $jCurr = $zetaCurr\n")
        }
    }
    return sb.toString()
}
